/* AM2050 — Field Ledger Modernism reinterpreted as a premium civic command access screen: dark full-bleed operating canvas, dominant institutional mark, and a concise credential dock. */
import { FormEvent, useState } from "react";
import { Eye, EyeOff, LockKeyhole, UserRound } from "lucide-react";
import { LogoMark } from "@/components/brand/LogoMark";
import { useAuth } from "@/contexts/AuthContext";
import { useLocation } from "wouter";

export default function Login() {
  const { login } = useAuth();
  const [, setLocation] = useLocation();
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSubmitting(true); setError(""); const result = await login(phone, password); if (result.success) setLocation("/workspace"); else setError(result.error || "Unable to sign in. Check your details and try again."); setSubmitting(false); };

  return <main className="relative min-h-screen overflow-hidden bg-[#0d2d40] text-white"><img src="/manus-storage/am2050-geography-ledger_56695637.jpg" alt="" className="absolute inset-0 h-full w-full object-cover opacity-[.12] mix-blend-luminosity"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_26%,rgba(72,137,111,.36),transparent_23%),radial-gradient(circle_at_84%_76%,rgba(200,139,37,.14),transparent_22%),linear-gradient(135deg,rgba(7,30,45,.22),rgba(7,30,45,.84))]"/><div className="absolute inset-x-0 top-[18%] h-px bg-white/10"/><div className="absolute left-[8%] top-[18%] h-[58%] w-px bg-white/10"/><div className="absolute -left-32 bottom-[-15rem] size-[42rem] rounded-full border border-[#9cc8ae]/20"/><div className="absolute -left-12 bottom-[-5rem] size-[27rem] rounded-full border border-white/10"/>
    <div className="relative z-10 mx-auto flex min-h-screen max-w-[1540px] flex-col px-6 py-6 sm:px-10 sm:py-9 lg:px-16 lg:py-11"><header><div className="flex items-center gap-5"><span className="grid size-[4.5rem] place-items-center rounded-full bg-[#fbfaf6] shadow-[0_0_0_7px_rgba(156,200,174,.16)]"><LogoMark size={49}/></span><div><div className="leading-none"><strong className="font-display text-[1.9rem] font-semibold tracking-[.14em]">AM</strong><span className="ml-1 font-mono text-[1.32rem] tracking-[.12em] text-[#a7d6b7]">2050</span></div><span className="mt-1.5 block font-mono text-[.55rem] uppercase tracking-[.18em] text-white/55">Arewa Mission</span></div></div></header>
      <section className="grid flex-1 items-center gap-12 py-12 lg:grid-cols-[minmax(0,1fr)_minmax(25rem,30rem)] lg:gap-24 lg:py-0"><div className="relative max-w-3xl"><div className="mt-9"><p className="font-mono text-[.62rem] uppercase tracking-[.22em] text-[#a7d6b7]">Northern Nigeria</p><div className="mt-3 flex items-end gap-4"><span className="font-display text-[clamp(5rem,15vw,12rem)] font-semibold leading-[.72] tracking-[-.09em] text-white">AM</span><span className="mb-1.5 font-mono text-[clamp(2rem,5.3vw,4.8rem)] leading-none tracking-[.04em] text-[#a7d6b7]">2050</span></div></div><div className="mt-12 flex max-w-lg items-center gap-4"><span className="h-px flex-1 bg-white/25"/><span className="size-2 bg-[#167a4c]"/><span className="h-px w-16 bg-white/25"/></div></div>
        <div className="w-full border border-white/20 border-l-[6px] border-l-[#c88b25] bg-[#f7f4ed] p-7 text-[#123148] sm:p-9"><div className="border-b border-[#cbd6cf] pb-6"><h1 className="font-display text-3xl font-semibold tracking-[-.06em]">Login</h1></div><form onSubmit={submit} className="mt-7 border-y border-[#cbd6cf]"><label className="block border-b border-[#d8e0da] py-5"><span className="mb-2 block font-mono text-[.62rem] font-semibold uppercase tracking-[.12em] text-[#34566b]">Staff phone number</span><div className="relative"><UserRound size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#718592]"/><input className="h-13 w-full rounded-none border border-[#b9c9c0] bg-white px-4 pl-11 text-base text-[#123148] outline-none transition focus:border-[#167a4c] focus:ring-2 focus:ring-[#167a4c]/15" value={phone} onChange={(event) => setPhone(event.target.value)} inputMode="tel" autoComplete="tel" placeholder="0800 000 0000" required/></div></label><label className="block py-5"><span className="mb-2 block font-mono text-[.62rem] font-semibold uppercase tracking-[.12em] text-[#34566b]">Password</span><div className="relative"><LockKeyhole size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#718592]"/><input className="h-13 w-full rounded-none border border-[#b9c9c0] bg-white px-11 text-base text-[#123148] outline-none transition focus:border-[#167a4c] focus:ring-2 focus:ring-[#167a4c]/15" value={password} onChange={(event) => setPassword(event.target.value)} type={showPassword ? "text" : "password"} autoComplete="current-password" placeholder="Enter your password" required/><button type="button" onClick={() => setShowPassword((value) => !value)} className="absolute right-3 top-1/2 grid size-8 -translate-y-1/2 place-items-center text-[#56727f] transition hover:text-[#123148]" aria-label={showPassword ? "Hide password" : "Show password"}>{showPassword ? <EyeOff size={18}/> : <Eye size={18}/>}</button></div></label>{error ? <p role="alert" className="mb-5 border-l-[3px] border-[#ae3f32] bg-[#f9e8e5] px-3 py-3 text-sm text-[#8d3027]">{error}</p> : null}<div className="border-t border-[#d8e0da] py-5"><button type="submit" disabled={submitting} className="action-press flex h-13 w-full items-center justify-center bg-[#167a4c] px-5 text-sm font-semibold text-white transition hover:bg-[#12683f] disabled:opacity-70">{submitting ? "Signing in…" : "Login"}</button></div></form></div>
      </section><footer className="flex items-center gap-3 font-mono text-[.55rem] uppercase tracking-[.16em] text-white/45"><span className="h-px w-8 bg-[#c88b25]"/><span>AM2050</span></footer>
    </div>
  </main>;
}
