<?php
declare(strict_types=1);

namespace AM2050\Services;

use AM2050\Core\Database;
use AM2050\Support\ScopeFilter;
use PDO;

final class InsightService
{
    public function __construct(private readonly Database $db) {}
    private function wards(array $auth, string $column): array { return ScopeFilter::byWard($auth, $column); }

    public function dashboard(array $auth): array { $pdo=$this->db->pdo();if(in_array($auth['assigned_scope_type']??null,['school','class'],true)){[$scope,$params]=$this->educationScope($auth,'s.ward_id','e.school_id','e.class_id');$total=$pdo->prepare('SELECT COUNT(DISTINCT e.child_id) FROM enrollments e INNER JOIN children c ON c.id=e.child_id WHERE c.child_status="active" AND e.enrollment_status IN ("active","pending")'.$scope);$total->execute($params);$all=(int)$total->fetchColumn();$enrolled=$pdo->prepare('SELECT COUNT(DISTINCT e.child_id) FROM enrollments e WHERE e.enrollment_status="active"'.$scope);$enrolled->execute($params);$active=(int)$enrolled->fetchColumn();$followUp=$pdo->prepare('SELECT COUNT(DISTINCT e.child_id) FROM enrollments e INNER JOIN children c ON c.id=e.child_id WHERE c.child_status="active" AND e.enrollment_status!="active"'.$scope);$followUp->execute($params);$registeredNotEnrolled=(int)$followUp->fetchColumn();[$attendanceScope,$attendanceParams]=$this->educationScope($auth,'s.ward_id','a.school_id','a.class_id');$attendance=$pdo->prepare('SELECT COALESCE(AVG(a.attendance_status IN ("present","late"))*100,0) FROM attendance a WHERE a.date>=DATE_SUB(CURDATE(),INTERVAL 7 DAY)'.$attendanceScope);$attendance->execute($attendanceParams);$rate=(float)$attendance->fetchColumn();return['totalChildren'=>$all,'activeEnrollment'=>$active,'enrollmentRate'=>$all?round($active/$all*100,2):0,'attendanceRate'=>round($rate,2),'registeredNotEnrolled'=>$registeredNotEnrolled];}[$scope,$params]=$this->wards($auth,'COALESCE(h.ward_id,c.ward_id)');$children=' FROM children c LEFT JOIN households h ON h.id=c.household_id WHERE c.child_status="active"';$total=$pdo->prepare('SELECT COUNT(*)'.$children.$scope);$total->execute($params);$all=(int)$total->fetchColumn();$enrolled=$pdo->prepare('SELECT COUNT(DISTINCT e.child_id) FROM enrollments e INNER JOIN children c ON c.id=e.child_id LEFT JOIN households h ON h.id=c.household_id WHERE e.enrollment_status="active"'.$scope);$enrolled->execute($params);$active=(int)$enrolled->fetchColumn();$attendance=$pdo->prepare('SELECT COALESCE(AVG(a.attendance_status IN ("present","late"))*100,0) FROM attendance a INNER JOIN children c ON c.id=a.child_id LEFT JOIN households h ON h.id=c.household_id WHERE a.date>=DATE_SUB(CURDATE(),INTERVAL 7 DAY)'.$scope);$attendance->execute($params);$rate=(float)$attendance->fetchColumn();return['totalChildren'=>$all,'activeEnrollment'=>$active,'enrollmentRate'=>$all?round($active/$all*100,2):0,'attendanceRate'=>round($rate,2),'registeredNotEnrolled'=>max(0,$all-$active)]; }
    public function outOfSchool(array $auth): array { [$scope,$params]=$this->wards($auth,'COALESCE(h.ward_id,c.ward_id)');$sql='SELECT c.id,c.child_unique_id,c.first_name,c.last_name,c.gender,COALESCE(h.ward_id,c.ward_id) AS ward_id FROM children c LEFT JOIN households h ON h.id=c.household_id WHERE c.child_status="active" AND NOT EXISTS (SELECT 1 FROM enrollments e WHERE e.child_id=c.id AND e.enrollment_status="active")'.$scope.' ORDER BY c.created_at DESC';$stmt=$this->db->pdo()->prepare($sql);$stmt->execute($params);$registered=$stmt->fetchAll();[$reportedScope,$reportedParams]=$this->wards($auth,'h.ward_id');$report=$this->db->pdo()->prepare('SELECT u.* FROM unregistered_child_reports u INNER JOIN households h ON h.id=u.household_id WHERE u.status="reported"'.$reportedScope.' ORDER BY u.created_at DESC');$report->execute($reportedParams);$unregistered=$report->fetchAll();return['registeredNotEnrolled'=>$registered,'reportedUnregistered'=>$unregistered,'total'=>count($registered)+count($unregistered)]; }
    public function defaulters(array $auth,array $query):array { [$scope,$params]=$this->educationScope($auth,'s.ward_id','s.id','a.class_id');$sql='SELECT c.id,c.child_unique_id,c.first_name,c.last_name,c.guardian_phone,MAX(a.date) AS last_absence,COUNT(*) AS absences FROM attendance a INNER JOIN children c ON c.id=a.child_id INNER JOIN schools s ON s.id=a.school_id WHERE a.attendance_status="absent" AND a.date>=DATE_SUB(CURDATE(),INTERVAL 14 DAY)'.$scope.' GROUP BY c.id HAVING COUNT(*)>=3 ORDER BY absences DESC';$stmt=$this->db->pdo()->prepare($sql);$stmt->execute($params);return$stmt->fetchAll(); }
    public function attendanceTrend(array $auth):array { if(in_array($auth['assigned_scope_type']??null,['school','class'],true)){[$scope,$params]=$this->educationScope($auth,'s.ward_id','a.school_id','a.class_id');$stmt=$this->db->pdo()->prepare('SELECT a.date,ROUND(AVG(a.attendance_status IN ("present","late"))*100,2) AS attendance_rate FROM attendance a WHERE a.date>=DATE_SUB(CURDATE(),INTERVAL 30 DAY)'.$scope.' GROUP BY a.date ORDER BY a.date');$stmt->execute($params);return$stmt->fetchAll();}[$scope,$params]=$this->wards($auth,'COALESCE(h.ward_id,c.ward_id)');$stmt=$this->db->pdo()->prepare('SELECT a.date,ROUND(AVG(a.attendance_status IN ("present","late"))*100,2) AS attendance_rate FROM attendance a INNER JOIN children c ON c.id=a.child_id LEFT JOIN households h ON h.id=c.household_id WHERE a.date>=DATE_SUB(CURDATE(),INTERVAL 30 DAY)'.$scope.' GROUP BY a.date ORDER BY a.date');$stmt->execute($params);return$stmt->fetchAll(); }
    public function heatMap(array $auth):array { [$scope,$params]=$this->wards($auth,'w.id');$sql='SELECT w.id,w.name AS ward_name,COUNT(DISTINCT c.id) AS total_children,COUNT(DISTINCT CASE WHEN c.id IS NOT NULL AND e.id IS NULL THEN c.id END) AS out_of_school_children FROM wards w LEFT JOIN households h ON h.ward_id=w.id LEFT JOIN children c ON c.ward_id=w.id OR c.household_id=h.id LEFT JOIN enrollments e ON e.child_id=c.id AND e.enrollment_status="active" WHERE 1=1'.$scope.' GROUP BY w.id,w.name ORDER BY out_of_school_children DESC,w.name';$stmt=$this->db->pdo()->prepare($sql);$stmt->execute($params);return$stmt->fetchAll(); }
    public function dropoutRisk(array $auth):array { [$scope,$params]=$this->educationScope($auth,'s.ward_id','s.id','a.class_id');$sql='SELECT c.id,c.child_unique_id,c.first_name,c.last_name,s.school_name,COUNT(CASE WHEN a.attendance_status="absent" AND a.date>=DATE_SUB(CURDATE(),INTERVAL 14 DAY) THEN 1 END) AS recent_absences,COUNT(CASE WHEN a.attendance_status="absent" AND a.date>=DATE_SUB(CURDATE(),INTERVAL 30 DAY) THEN 1 END) AS monthly_absences FROM children c INNER JOIN enrollments e ON e.child_id=c.id AND e.enrollment_status="active" INNER JOIN schools s ON s.id=e.school_id LEFT JOIN attendance a ON a.child_id=c.id WHERE 1=1'.$scope.' GROUP BY c.id,s.school_name HAVING recent_absences>=2 OR monthly_absences>=4 ORDER BY recent_absences DESC,monthly_absences DESC';$stmt=$this->db->pdo()->prepare($sql);$stmt->execute($params);return array_map(static fn(array $row)=>[...$row,'risk_level'=>(int)$row['recent_absences']>=4||(int)$row['monthly_absences']>=7?'high':'moderate'],$stmt->fetchAll()); }
    public function roi():array { $pdo=$this->db->pdo();$children=(int)$pdo->query('SELECT COUNT(*) FROM children WHERE child_status="active"')->fetchColumn();$enrolled=(int)$pdo->query('SELECT COUNT(DISTINCT child_id) FROM enrollments WHERE enrollment_status="active"')->fetchColumn();$disbursed=(float)$pdo->query('SELECT COALESCE(SUM(CASE WHEN payment_status="disbursed" THEN 1 ELSE 0 END),0) FROM incentives')->fetchColumn();$amount=(float)json_decode((string)$pdo->query("SELECT rule_value FROM program_rules WHERE rule_key='incentiveAmount'")->fetchColumn(),true);$cost=$disbursed*$amount;return['activeChildren'=>$children,'activeEnrollment'=>$enrolled,'enrollmentRate'=>$children?round($enrolled/$children*100,2):0,'recordedIncentiveCost'=>$cost,'costPerEnrolledChild'=>$enrolled?round($cost/$enrolled,2):0,'methodology'=>'Recorded incentive disbursements multiplied by the configured incentive amount; excludes unrecorded delivery and operating costs.']; }
    /** Decision-ready dashboard model. Raw source records remain authoritative. */
    public function decisionDashboard(array $auth): array {
        $base=$this->dashboard($auth); $pdo=$this->db->pdo(); $now=gmdate('c');
        [$attendanceScope,$attendanceParams]=$this->educationScope($auth,'s.ward_id','a.school_id','a.class_id');
        $attendance=$pdo->prepare('SELECT COUNT(*) AS denominator,COALESCE(SUM(a.attendance_status IN ("present","late")),0) AS numerator,MAX(a.date) AS freshness FROM attendance a INNER JOIN schools s ON s.id=a.school_id WHERE a.date>=DATE_SUB(CURDATE(),INTERVAL 7 DAY)'.$attendanceScope);$attendance->execute($attendanceParams);$attendanceMeta=$attendance->fetch() ?: ['denominator'=>0,'numerator'=>0,'freshness'=>null];
        $configured=(bool)$pdo->query('SELECT EXISTS(SELECT 1 FROM terms WHERE status="active")')->fetchColumn();
        $attendanceState=(int)$attendanceMeta['denominator']===0?($configured?'no_data':'not_configured'):((int)$attendanceMeta['numerator']===0?'zero':'ready');
        $childrenState=$base['totalChildren']===0?'zero':'ready';
        $enrollmentState=$base['totalChildren']===0?'no_data':($base['activeEnrollment']===0?'zero':'ready');
        $followupState=$base['totalChildren']===0?'no_data':($base['registeredNotEnrolled']===0?'zero':'ready');
        $trend=$this->attendanceTrend($auth); $recent=array_slice($trend,-7);$prior=array_slice($trend,-14,7);$recentRate=$recent?array_sum(array_map(static fn($r)=>(float)$r['attendance_rate'],$recent))/count($recent):null;$priorRate=$prior?array_sum(array_map(static fn($r)=>(float)$r['attendance_rate'],$prior))/count($prior):null;
        return ['generatedAt'=>$now,'metrics'=>[
            ['key'=>'children','label'=>'Registered children','value'=>$base['totalChildren'],'format'=>'count','numerator'=>$base['totalChildren'],'denominator'=>null,'dateRange'=>'Current active registry','freshness'=>$this->latestChildFreshness($auth),'state'=>$childrenState,'methodology'=>'Active child records in your authorised scope.'],
            ['key'=>'enrollment','label'=>'Active enrollment','value'=>$base['enrollmentRate'],'format'=>'percent','numerator'=>$base['activeEnrollment'],'denominator'=>$base['totalChildren'],'dateRange'=>'Current active placements','freshness'=>$this->latestEnrollmentFreshness($auth),'state'=>$enrollmentState,'methodology'=>'Children with an active school placement divided by active registered children.'],
            ['key'=>'attendance','label'=>'Attendance, last 7 days','value'=>$attendanceMeta['denominator']?round(((int)$attendanceMeta['numerator']/(int)$attendanceMeta['denominator'])*100,2):0,'format'=>'percent','numerator'=>(int)$attendanceMeta['numerator'],'denominator'=>(int)$attendanceMeta['denominator'],'dateRange'=>'Last 7 calendar days','freshness'=>$attendanceMeta['freshness'],'state'=>$attendanceState,'methodology'=>'Present or late attendance entries divided by all recorded attendance entries; excused and absent entries remain in the denominator.'],
            ['key'=>'followup','label'=>'Awaiting enrollment','value'=>$base['registeredNotEnrolled'],'format'=>'count','numerator'=>$base['registeredNotEnrolled'],'denominator'=>$base['totalChildren'],'dateRange'=>'Current active registry','freshness'=>$this->latestChildFreshness($auth),'state'=>$followupState,'methodology'=>'Active registered children without an active school placement.'],
        ],'trend'=>['series'=>$trend,'dateRange'=>'Last 30 calendar days','state'=>$trend? 'ready':($configured?'no_data':'not_configured'),'change'=>$recentRate===null||$priorRate===null?null:round($recentRate-$priorRate,2),'recentAverage'=>$recentRate===null?null:round($recentRate,2),'previousAverage'=>$priorRate===null?null:round($priorRate,2),'methodology'=>'Daily attendance rate: present or late entries divided by all recorded attendance entries for that date.'],'priorityQueue'=>$this->priorityQueue($auth),'dataStates'=>['ready'=>'Recorded data is available.','zero'=>'The measured value is zero for the stated population and date range.','no_data'=>'No eligible source records are available for this measure.','not_configured'=>'This measure cannot be calculated until its required programme configuration exists.','syncing'=>'Local field records are waiting to synchronize; server metrics may be incomplete.']];
    }
    public function metricDrilldown(array $auth,string $metric): array {
        $allowed=['children','enrollment','attendance','followup'];if(!in_array($metric,$allowed,true))throw new \RuntimeException('Unsupported dashboard metric.');$pdo=$this->db->pdo();
        if($metric==='attendance'){[$scope,$params]=$this->educationScope($auth,'s.ward_id','a.school_id','a.class_id');$sql='SELECT c.child_unique_id,CONCAT(c.first_name," ",c.last_name) AS child_name,s.school_name,sc.class_name,a.date,a.attendance_status FROM attendance a INNER JOIN children c ON c.id=a.child_id INNER JOIN schools s ON s.id=a.school_id LEFT JOIN school_classes sc ON sc.id=a.class_id WHERE a.date>=DATE_SUB(CURDATE(),INTERVAL 7 DAY)'.$scope.' ORDER BY a.date DESC,child_name';$stmt=$pdo->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();return['key'=>$metric,'label'=>'Attendance entries','dateRange'=>'Last 7 calendar days','freshness'=>$rows[0]['date']??null,'columns'=>['Child ID','Child','School','Class','Date','Attendance status'],'rows'=>array_map(static fn($r)=>[$r['child_unique_id'],$r['child_name'],$r['school_name'],$r['class_name']??'—',$r['date'],$r['attendance_status']],$rows),'includedCount'=>count($rows),'excludedCount'=>0,'state'=>$rows?'ready':'no_data'];}
        [$scope,$params]=$this->dashboardChildScope($auth);$from=' FROM children c LEFT JOIN households h ON h.id=c.household_id LEFT JOIN enrollments e ON e.child_id=c.id AND e.enrollment_status="active" LEFT JOIN schools s ON s.id=e.school_id LEFT JOIN school_classes sc ON sc.id=e.class_id';$where=' WHERE c.child_status="active"'.$scope;
        if($metric==='enrollment')$where.=' AND e.id IS NOT NULL';if($metric==='followup')$where.=' AND e.id IS NULL';
        $stmt=$pdo->prepare('SELECT c.child_unique_id,CONCAT(c.first_name," ",c.last_name) AS child_name,c.created_at,s.school_name,sc.class_name,c.duplicate_flag'.$from.$where.' ORDER BY c.created_at DESC');$stmt->execute($params);$rows=$stmt->fetchAll();$columns=$metric==='children'?['Child ID','Child','Current school','Class','Verification','Duplicate flag','Registered']:['Child ID','Child','School','Class','Registered'];$mapped=array_map(static function($row)use($metric){$base=[$row['child_unique_id'],$row['child_name'],$row['school_name']??'—',$row['class_name']??'—'];if($metric==='children'){$base[]='Active';$base[]=$row['duplicate_flag']?'Review required':'No flag';}$base[]=$row['created_at'];return$base;},$rows);return['key'=>$metric,'label'=>$metric==='children'?'Registered child records':($metric==='enrollment'?'Active enrollment records':'Children awaiting enrollment'),'dateRange'=>'Current active registry','freshness'=>$rows[0]['created_at']??null,'columns'=>$columns,'rows'=>$mapped,'includedCount'=>count($mapped),'excludedCount'=>0,'state'=>$mapped?'ready':'no_data'];
    }
    public function priorityQueue(array $auth): array {
        $items=[];$now=new \DateTimeImmutable('today');
        $targets=$this->dashboardSlaTargets();$assignments=$this->priorityAssignments();
        foreach($this->registeredNotEnrolled($auth,8) as $row){$age=max(0,(int)$now->diff(new \DateTimeImmutable($row['created_at']))->format('%r%a'));$key='enrollment-'.$row['id'];$assignment=$assignments[$key]??null;$items[]=['id'=>$key,'priorityType'=>'enrollment_followup','severity'=>$this->severity($age,$targets['enrollment_followup']),'openedAt'=>$row['created_at'],'ageDays'=>$age,'ownerId'=>$assignment['owner_user_id']??null,'owner'=>$assignment['owner_name']??'Unassigned','nextAction'=>'Confirm school placement','actionPath'=>'/enrollments','source'=>'Child Register','summary'=>$row['first_name'].' '.$row['last_name'].' is registered without an active placement.','sla'=>$this->slaLabel($age,$targets['enrollment_followup'])];}
        foreach($this->defaulters($auth,[]) as $row){$age=max(0,(int)$now->diff(new \DateTimeImmutable($row['last_absence']))->format('%r%a'));$key='attendance-'.$row['id'];$assignment=$assignments[$key]??null;$items[]=['id'=>$key,'priorityType'=>'attendance_followup','severity'=>$this->severity($age,$targets['attendance_followup']),'openedAt'=>$row['last_absence'],'ageDays'=>$age,'ownerId'=>$assignment['owner_user_id']??null,'owner'=>$assignment['owner_name']??'Unassigned','nextAction'=>'Review attendance and record follow-up','actionPath'=>'/defaulters','source'=>'Attendance Register','summary'=>$row['first_name'].' '.$row['last_name'].' has '.$row['absences'].' absences in the last 14 days.','sla'=>$this->slaLabel($age,$targets['attendance_followup'])];}
        usort($items,static fn($a,$b)=>['high'=>3,'medium'=>2,'low'=>1][$b['severity']]<=>['high'=>3,'medium'=>2,'low'=>1][$a['severity']] ?: $b['ageDays']<=>$a['ageDays']);return array_slice($items,0,12);
    }
    private function registeredNotEnrolled(array $auth,int $limit): array {[$scope,$params]=$this->dashboardChildScope($auth);$stmt=$this->db->pdo()->prepare('SELECT c.id,c.first_name,c.last_name,c.created_at FROM children c LEFT JOIN households h ON h.id=c.household_id WHERE c.child_status="active"'.$scope.' AND NOT EXISTS (SELECT 1 FROM enrollments ne WHERE ne.child_id=c.id AND ne.enrollment_status="active") ORDER BY c.created_at ASC LIMIT :limit');foreach($params as $key=>$value)$stmt->bindValue(':'.$key,$value);$stmt->bindValue(':limit',$limit,PDO::PARAM_INT);$stmt->execute();return$stmt->fetchAll();}
    private function dashboardChildScope(array $auth): array {$role=$auth['role']??'';$scope=$auth['assigned_scope_id']??null;if(in_array($role,['super_admin','program_admin'],true))return['',[]];if(($auth['assigned_scope_type']??'')==='school')return[' AND EXISTS (SELECT 1 FROM enrollments de WHERE de.child_id=c.id AND de.school_id=:scope_id)',['scope_id'=>$scope]];if(($auth['assigned_scope_type']??'')==='class')return[' AND EXISTS (SELECT 1 FROM enrollments de WHERE de.child_id=c.id AND de.class_id=:scope_id)',['scope_id'=>$scope]];return ScopeFilter::byWard($auth,'COALESCE(h.ward_id,c.ward_id)');}
    private function latestChildFreshness(array $auth): ?string {[$scope,$params]=$this->dashboardChildScope($auth);$stmt=$this->db->pdo()->prepare('SELECT MAX(c.updated_at) FROM children c LEFT JOIN households h ON h.id=c.household_id WHERE c.child_status="active"'.$scope);$stmt->execute($params);return$stmt->fetchColumn()?:null;}
    private function latestEnrollmentFreshness(array $auth): ?string {[$scope,$params]=$this->educationScope($auth,'s.ward_id','e.school_id','e.class_id');$stmt=$this->db->pdo()->prepare('SELECT MAX(e.updated_at) FROM enrollments e INNER JOIN schools s ON s.id=e.school_id WHERE e.enrollment_status="active"'.$scope);$stmt->execute($params);return$stmt->fetchColumn()?:null;}
    private function dashboardSlaTargets():array{$stmt=$this->db->pdo()->prepare('SELECT rule_value FROM program_rules WHERE rule_key="dashboardSlaTargets"');$stmt->execute();$value=json_decode((string)$stmt->fetchColumn(),true);return is_array($value)?$value:['enrollment_followup'=>14,'attendance_followup'=>7];}
    private function priorityAssignments():array{$rows=$this->db->pdo()->query('SELECT a.priority_key,a.owner_user_id,u.name AS owner_name FROM dashboard_priority_assignments a LEFT JOIN users u ON u.id=a.owner_user_id')->fetchAll();$out=[];foreach($rows as$row)$out[$row['priority_key']]=$row;return$out;}
    private function severity(int $age,int $target):string{return $age>=$target?'high':($age>=max(1,(int)ceil($target*.5))?'medium':'low');}
    private function slaLabel(int $age,int $target):string{return $age>=$target?'Overdue':($age>=max(1,(int)ceil($target*.75))?'Due soon':'Within target');}
    private function educationScope(array $auth,string $wardColumn,string $schoolColumn,string $classColumn):array { if(in_array($auth['role'],['super_admin','program_admin'],true))return['',[]];$scope=$auth['assigned_scope_id']??null;return match($auth['assigned_scope_type']??null){'school'=>[" AND {$schoolColumn}=:scope_id",['scope_id'=>$scope]],'class'=>[" AND {$classColumn}=:scope_id",['scope_id'=>$scope]],default=>ScopeFilter::byWard($auth,$wardColumn)}; }
}
