<?php
declare(strict_types=1);
namespace AM2050\Controllers;
use AM2050\Core\Database;use AM2050\Core\Request;use AM2050\Core\Response;use AM2050\Middleware\AuthMiddleware;use AM2050\Middleware\RoleMiddleware;use AM2050\Support\ScopeFilter;use AM2050\Support\Ulids;
final class ReportController{
 public function __construct(private readonly AuthMiddleware $auth,private readonly Database $db){}
 private function actor(Request $r,array $roles):array{$a=$this->auth->require($r);RoleMiddleware::allow($a,$roles);return$a;}
 private function scope(array $a,string $ward,?string $headmasterClause=null,?string $teacherClause=null):array{if($a['role']==='headmaster'&&$headmasterClause!==null)return[' AND '.$headmasterClause,['scope_id'=>$a['assigned_scope_id']]];if($a['role']==='teacher'&&$teacherClause!==null)return[' AND '.$teacherClause,['scope_id'=>$a['assigned_scope_id']]];return in_array($a['role'],['super_admin','program_admin'],true)?['',[]]:ScopeFilter::byWard($a,$ward);}
 private function output(Request $r,string $title,string $slug,array $headers,array $rows):never{$format=$r->query['format']??'csv';$safe=array_map(fn($row)=>array_map(static fn($v)=>is_string($v)&&preg_match('/^[=+\-@]/',$v)?"'".$v:$v,$row),$rows);if($format==='xlsx'){header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="am2050-'.$slug.'.xlsx"');$sheet=(new \PhpOffice\PhpSpreadsheet\Spreadsheet())->getActiveSheet();$sheet->fromArray($headers,null,'A1');$sheet->fromArray($safe,null,'A2');$sheet->getStyle('A1:Z1')->getFont()->setBold(true);(new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($sheet->getParent()))->save('php://output');exit;}if($format==='pdf'){header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="am2050-'.$slug.'.pdf"');$html='<h1>'.htmlspecialchars($title).'</h1><table border="1" cellspacing="0" cellpadding="4"><thead><tr>';foreach($headers as$h)$html.='<th>'.htmlspecialchars((string)$h).'</th>';$html.='</tr></thead><tbody>';foreach($safe as$row){$html.='<tr>';foreach($row as$v)$html.='<td>'.htmlspecialchars((string)$v).'</td>';$html.='</tr>';}$html.='</tbody></table>';$pdf=new \Dompdf\Dompdf();$pdf->loadHtml($html);$pdf->setPaper('A4','landscape');$pdf->render();echo$pdf->output();exit;}header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="am2050-'.$slug.'.csv"');$out=fopen('php://output','w');fputcsv($out,$headers);foreach($safe as$row)fputcsv($out,$row);fclose($out);exit;}
 public function childRegistry(Request $r):never{$a=$this->actor($r,['super_admin','program_admin','lga_supervisor','ward_supervisor','headmaster']);[$scope,$params]=$this->scope($a,'COALESCE(h.ward_id,c.ward_id)','EXISTS (SELECT 1 FROM enrollments re WHERE re.child_id=c.id AND re.enrollment_status="active" AND re.school_id=:scope_id)');$stmt=$this->db->pdo()->prepare('SELECT c.child_unique_id,c.first_name,c.last_name,c.gender,c.date_of_birth,c.estimated_age,c.child_status,c.almajiri_status,h.household_code FROM children c LEFT JOIN households h ON h.id=c.household_id WHERE 1=1'.$scope.' ORDER BY c.child_unique_id');$stmt->execute($params);$this->output($r,'AM2050 Child Registry','child-registry',['Child ID','First name','Last name','Gender','Date of birth','Estimated age','Status','Almajiri status','Household code'],$stmt->fetchAll());}
 public function attendanceAlerts(Request $r):never{$a=$this->actor($r,['super_admin','program_admin','lga_supervisor','ward_supervisor','headmaster','teacher']);[$scope,$params]=$this->scope($a,'s.ward_id','s.id=:scope_id','e.class_id=:scope_id');$sql='SELECT c.child_unique_id,c.first_name,c.last_name,s.school_name,COUNT(CASE WHEN at.attendance_status="absent" AND at.date>=DATE_SUB(CURDATE(),INTERVAL 30 DAY) THEN 1 END) AS absences_30d FROM children c INNER JOIN enrollments e ON e.child_id=c.id AND e.enrollment_status="active" INNER JOIN schools s ON s.id=e.school_id LEFT JOIN attendance at ON at.child_id=c.id WHERE 1=1'.$scope.' GROUP BY c.id,s.school_name HAVING absences_30d>=3 ORDER BY absences_30d DESC';$stmt=$this->db->pdo()->prepare($sql);$stmt->execute($params);$this->output($r,'AM2050 Attendance Alerts','attendance-alerts',['Child ID','First name','Last name','School','Absences in 30 days'],$stmt->fetchAll());}
 public function resultsSummary(Request $r):never{$a=$this->actor($r,['super_admin','program_admin','lga_supervisor','ward_supervisor','headmaster','teacher']);[$scope,$params]=$this->scope($a,'s.ward_id','s.id=:scope_id','e.class_id=:scope_id');$sql='SELECT s.school_name,t.academic_year,t.term_name,r.subject,COUNT(r.id) AS results_recorded,ROUND(AVG(r.score),2) AS average_score FROM student_results r INNER JOIN enrollments e ON e.id=r.enrollment_id INNER JOIN schools s ON s.id=e.school_id INNER JOIN terms t ON t.id=r.term_id WHERE 1=1'.$scope.' GROUP BY s.school_name,t.academic_year,t.term_name,r.subject ORDER BY t.academic_year DESC,t.term_name,s.school_name,r.subject';$stmt=$this->db->pdo()->prepare($sql);$stmt->execute($params);$this->output($r,'AM2050 Results Summary','results-summary',['School','Academic year','Term','Subject','Results recorded','Average score'],$stmt->fetchAll());}
 public function incentiveDisbursement(Request $r):never{$a=$this->actor($r,['super_admin','program_admin','lga_supervisor','ward_supervisor','headmaster']);[$scope,$params]=$this->scope($a,'COALESCE(h.ward_id,c.ward_id','EXISTS (SELECT 1 FROM enrollments re WHERE re.child_id=c.id AND re.enrollment_status="active" AND re.school_id=:scope_id)');$sql='SELECT c.child_unique_id,c.first_name,c.last_name,i.month,i.attendance_rate,i.eligibility_status,i.payment_status,i.disbursement_date,i.disbursement_reference FROM incentives i INNER JOIN children c ON c.id=i.child_id LEFT JOIN households h ON h.id=c.household_id WHERE i.payment_status="disbursed"'.$scope.' ORDER BY i.disbursement_date DESC';$stmt=$this->db->pdo()->prepare($sql);$stmt->execute($params);$this->output($r,'AM2050 Incentive Disbursements','incentive-disbursements',['Child ID','First name','Last name','Month','Attendance rate','Eligibility','Payment status','Disbursement date','Reference'],$stmt->fetchAll());}
 public function schedules(Request $r):never{$a=$this->actor($r,['super_admin','program_admin']);$stmt=$this->db->pdo()->prepare('SELECT rs.*,u.full_name AS created_by_name FROM report_schedules rs INNER JOIN users u ON u.id=rs.created_by WHERE rs.created_by=:user OR :admin=1 ORDER BY rs.created_at DESC');$stmt->execute(['user'=>$a['id'],'admin'=>$a['role']==='super_admin'?1:0]);Response::success($stmt->fetchAll());}
 public function createSchedule(Request $r):never{$a=$this->actor($r,['super_admin','program_admin']);$d=$r->body();if(!in_array($d['reportType']??'', ['attendance_alerts','results_summary','incentive_disbursements'],true)||!in_array($d['frequency']??'', ['weekly','monthly'],true)||!filter_var($d['deliveryEmail']??'',FILTER_VALIDATE_EMAIL))Response::error('Provide a supported report type, weekly/monthly frequency, and valid recipient email.',422);$id=Ulids::make();$this->db->pdo()->prepare('INSERT INTO report_schedules(id,report_type,frequency,delivery_email,created_by) VALUES(:id,:type,:frequency,:email,:user)')->execute(['id'=>$id,'type'=>$d['reportType'],'frequency'=>$d['frequency'],'email'=>$d['deliveryEmail'],'user'=>$a['id']]);Response::success(['id'=>$id,'message'=>'Schedule definition saved. Automatic delivery is not enabled.'],201);}
 public function updateSchedule(Request $r,array $p):never{$a=$this->actor($r,['super_admin','program_admin']);$d=$r->body();if(!array_key_exists('isActive',$d))Response::error('isActive is required.',422);$stmt=$this->db->pdo()->prepare('UPDATE report_schedules SET is_active=:active WHERE id=:id AND (created_by=:user OR :admin=1)');$stmt->execute(['active'=>(bool)$d['isActive'],'id'=>$p['id'],'user'=>$a['id'],'admin'=>$a['role']==='super_admin'?1:0]);if($stmt->rowCount()===0)Response::error('Schedule not found or not authorised.',404);Response::success(['id'=>$p['id'],'isActive'=>(bool)$d['isActive']]);}
}
